### ISSUE TITLE
Read SPI EEPROM

### ISSUE THREAD

**Issue by otofoto** [nekromant/pygpiotools#1]
Looking for example to read SPI EEPROM using PL2303. 
Like this - https://github.com/gsimon75-iot/PL2303-GPIO/blob/master/spi_eeprom.cc

Also example to read external SMBUS/I²C EEPROM for PL2303HX as in PL2303 EEPROM Writer Application.

**Comment by nekromant** [comment]
Hello. This library only takes care of direct access to gpios. Bit-banging protocols is out of the scope of this small project. 

If you want to create something else on top of it, this should be another library or just use the solution you've linked.
